name: CI-FiapCloudGamesAPI

trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - develop

pool:
  name: LocalPoll

variables:
  buildConfiguration: 'Release'
  imageName: fiapcloudgamesapi
  dockerHubUser: 'gabrielpaulino'
  dockerHubPass: '@Kvg2hwq3'
  tag: $(Build.BuildId)

steps:
- task: UseDotNet@2
  inputs:
    packageType: sdk
    version: 9.0.x

- checkout: self

- task: DotNetCoreCLI@2
  displayName: 'Restore packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Só builda e publica a imagem se estiver na branch main
- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - script: |
      docker build -t $(dockerHubUser)/$(imageName):$(tag) .
    displayName: 'Docker Build'

  - script: |
      echo "$(dockerHubPass)" | docker login -u "$(dockerHubUser)" --password-stdin
    displayName: 'Docker Login'

  - script: |
      docker push $(dockerHubUser)/$(imageName):$(tag)
      docker tag $(dockerHubUser)/$(imageName):$(tag) $(dockerHubUser)/$(imageName):latest
      docker push $(dockerHubUser)/$(imageName):latest
    displayName: 'Docker Push'