stages:
- stage: Deploy
  displayName: 'Deploy da imagem Docker no Azure App Service'
  jobs:
  - deployment: DeployToAzure
    environment: 'production' 
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: UseDotNet@2
            displayName: 'Instalar .NET 8 SDK'
            inputs:
              packageType: sdk
              version: '8.0.x'

          - script: dotnet restore "$BUILD_SOURCESDIRECTORY/FiapCloudGamesAPI/FiapCloudGamesAPI.csproj" --configfile nuget.config
            displayName: 'Restore com NuGet oficial (sem feed privado)'

          - script: dotnet tool install --global dotnet-ef --configfile nuget.config
            displayName: 'Instalar dotnet-ef com nuget.config limpo'

          - script: echo "##vso[task.setvariable variable=PATH]$PATH:$HOME/.dotnet/tools"
            displayName: 'Atualizar PATH para usar dotnet-ef'

          - script: |
              echo "Rodando as migrations no banco Azure..."
              dotnet ef database update --project FiapCloudGamesAPI/FiapCloudGamesAPI.csproj
            displayName: 'Aplicar Migrations'
            env:
              ConnectionStrings__DefaultConnection: $(sql_string_connection)

          - task: AzureWebAppContainer@1
            displayName: 'Deploy Docker Image'
            inputs:
              azureSubscription: 'fiap-azure-connection'
              appName: 'fiap-cloudgames-api'
              imageName: $(dockerImage)
