trigger:
  branches:
    include:
      - main

pool:
  name: LocalPoll

variables:
  dockerImage: gabrielpaulino/fiapcloudgamesapi:latest

stages:
- stage: Deploy
  displayName: 'Deploy da imagem Docker no Azure App Service'
  jobs:
  - deployment: DeployToAzure
    environment: 'production' 
    strategy:
      runOnce:
        deploy:
          steps:
          
          # Etapa 1 - Instala SDK do .NET 9 (caso o agente não tenha)
          - task: UseDotNet@2
            displayName: 'Instalar .NET 9 SDK'
            inputs:
              packageType: sdk
              version: '9.0.x'

          - script: dotnet restore "$(Build.SourcesDirectory)\FiapCloudGamesAPI\FiapCloudGamesAPI.csproj" --configfile nuget.config
            displayName: 'Restore com NuGet oficial (sem feed privado)'

          - script: dotnet tool install --global dotnet-ef --configfile "$(Build.SourcesDirectory)\nuget.config"
            displayName: 'Instalar dotnet-ef com nuget.config limpo'

          # Etapa 2 - Adiciona path do dotnet-ef no ambiente
          - script: echo "##vso[task.setvariable variable=PATH]$PATH:$HOME/.dotnet/tools"
            displayName: 'Atualizar PATH para usar dotnet-ef'

          # Etapa 3 - Rodar as migrations no banco do Azure
          - script: |
              echo "Rodando as migrations no banco Azure..."
              dotnet ef database update --project FiapCloudGamesAPI/FiapCloudGamesAPI.csproj
            displayName: 'Aplicar Migrations'
            env:
              ConnectionStrings__Default: 'Server=fiap-cloudgames-server.database.windows.net;Database=FiapCloudGames;User Id=fiap-cloudgames-server-admin;Password=DY$lKVfRsCVRue6Y;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'

          # Etapa 4 - Deploy no Azure App Service com imagem Docker
          - task: AzureWebAppContainer@1
            displayName: 'Deploy Docker Image'
            inputs:
              azureSubscription: 'fiap-azure-connection'
              appName: 'fiap-cloudgames-api'
              imageName: $(dockerImage)
