trigger:
  branches:
    include:
      - main

pool:
  name: LocalPoll

variables:
  dockerImage: gabrielpaulino/fiapcloudgamesapi:latest

stages:
- stage: Deploy
  displayName: 'Deploy da imagem Docker no Azure App Service'
  jobs:
  - deployment: DeployToAzure
    environment: 'production' 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: 'Deploy Docker Image'
            inputs:
              azureSubscription: 'fiap-azure-connection'
              appName: 'fiap-cloudgames-api'
              imageName: $(dockerImage)